[package]
name = "day2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_driver = "0.3.6"
csv = "1.3.0"
nom = "7.1.3"
serde = "1.0.193"
serde_derive = "1.0.193"
